# Generated by Django 5.2.4 on 2025-09-02 08:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_fix_price_field'),
        ('users', '0003_alter_company_field_alter_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedservice',
            old_name='date_requested',
            new_name='requested_date',
        ),
        migrations.RemoveField(
            model_name='requestedservice',
            name='hours_requested',
        ),
        migrations.AddField(
            model_name='requestedservice',
            name='hours_needed',
            field=models.PositiveIntegerField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestedservice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_services', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.company'),
        ),
    ]
